<a href="https://colab.research.google.com/github/Stellalee32/python_programming/blob/main/Week11_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 2023272280 이승아

In [1]:
import numpy as np

a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [2]:
a = np.array([1,2,3,4,5,6])

In [3]:
a = np.array([[1,2,3,4,], [5,6,7,8], [9,10,11,12]])

In [4]:
print(a[0])

[1 2 3 4]


In [5]:
a = np.array([1,2,3])

In [6]:
np.zeros(2)

array([0., 0.])

In [7]:
np.ones(2)

array([1., 1.])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.empty(2)

array([1., 1.])

In [12]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [14]:
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [16]:
arr = np.array([2,1,5,3,7,4,6,8])

In [17]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [19]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

In [21]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [24]:
array_example.ndim

3

In [25]:
array_example.shape

(3, 2, 4)

In [26]:
a = np.arange(6)

In [27]:
print(a)

[0 1 2 3 4 5]


In [28]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [29]:
np.reshape(a, newshape=(1,6), order='c')

array([[0, 1, 2, 3, 4, 5]])

In [30]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [31]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [32]:
row_vector = a[np.newaxis, :]
row_vector.shape
(1,6)

(1, 6)

In [33]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [34]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [35]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [36]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [37]:
data = np.array([1, 2, 3])

In [38]:
data[1]

2

In [39]:
data[0:2]

array([1, 2])

In [40]:
data[1:]

array([2, 3])

In [41]:
data[-2:]

array([2, 3])

In [44]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [45]:
print(a[a < 5])

[1 2 3 4]


In [47]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [51]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [52]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [53]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [54]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [56]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [57]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [58]:
print(a[b])

[1 2 3 4]


In [59]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [61]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [64]:
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
               [4,4]])

In [66]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [67]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [68]:
x = np.arange(1, 25).reshape(2, 12)

In [69]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [70]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [71]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [72]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [73]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [75]:
b1[0] = 99

In [76]:
b1

array([99,  2,  3,  4])

In [77]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
b2 = a.copy()

In [79]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [80]:
data - ones

array([0, 1])

In [81]:
data * data

array([1, 4])

In [82]:
data / data

array([1., 1.])

In [83]:
a = np.array([1,2,3,4])
a.sum()

10

In [86]:
b = np.array([[1,1], [2,2]])
b.sum(axis=0)

array([3, 3])

In [87]:
b.sum(axis=1)

array([2, 4])

In [88]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [89]:
data.max()

2.0

In [90]:
data.min()

1.0

In [91]:
data.sum()

3.0

In [94]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [95]:
a.sum()

4.8595784

In [96]:
a.min()

0.05093587

In [97]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [98]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
data[0,1]

2

In [100]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [101]:
data[0:2, 0]

array([1, 3])

In [102]:
data.max()

6

In [103]:
data.min()

1

In [104]:
data.sum()

21

In [106]:
data = np.array([[1,2], [5,3], [4,6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [107]:
data.max(axis=0)

array([5, 6])

In [108]:
data.max(axis=1)

array([2, 5, 6])

In [109]:
data = np.array([[1,2], [3,4]])
ones = np.array([[1,1], [1,1]])
data + ones

array([[2, 3],
       [4, 5]])

In [110]:
data = np.array([[1,2],[3,4], [5,6]])
ones_row = np.array([[1,1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [111]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [112]:
np.ones(3)

array([1., 1., 1.])

In [113]:
np.zeros(3)

array([0., 0., 0.])

In [115]:
rng = np.random.default_rng()
rng.random(3)

array([0.80739262, 0.04138475, 0.76252755])

In [116]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [117]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [118]:
rng.random((3,2))

array([[0.67886211, 0.754242  ],
       [0.05109962, 0.16158506],
       [0.01269433, 0.52784705]])

In [119]:
rng.integers(5, size=(2,4))

array([[0, 0, 1, 4],
       [1, 0, 4, 2]])

In [120]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [121]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [122]:
unique_values, indices_list = np.unique(a, return_index = True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [124]:
unique_values, occurence_count = np.unique(a, return_counts=True)
print(occurence_count)

[3 2 2 2 1 1 1 1 1 1]


In [126]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [127]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [128]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [129]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [130]:
print(indices)

[0 1 2]


In [131]:
print(occurrence_count)

[2 1 1]


In [132]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [134]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [135]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [136]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [137]:
arr = np.array([1,2,3,4,5,6,7,8])

In [138]:
reversed_arr = np.flip(arr)

In [139]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [141]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [142]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [143]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [144]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [145]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [146]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [147]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [148]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [149]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [150]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [151]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
